# Generated by Django 5.1.4 on 2025-07-19 17:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('user', 'ผู้ใช้ทั่วไป'), ('admin', 'ผู้ดูแลระบบ'), ('superuser', 'ผู้ดูแลระบบสูงสุด')], default='user', help_text='ระดับสิทธิ์การใช้งาน', max_length=10, verbose_name='ประเภทผู้ใช้')),
                ('daily_conversion_limit', models.IntegerField(default=50, help_text='จำนวนครั้งสูงสุดที่แปลงภาพได้ต่อวัน', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='จำกัดการแปลงต่อวัน')),
                ('daily_conversions_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='จำนวนการแปลงที่ใช้วันนี้')),
                ('last_conversion_date', models.DateField(blank=True, null=True, verbose_name='วันที่แปลงครั้งล่าสุด')),
                ('total_conversions', models.IntegerField(default=0, verbose_name='จำนวนการแปลงทั้งหมด')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้',
                'verbose_name_plural': 'ผู้ใช้',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'ข้อมูล'), ('warning', 'คำเตือน'), ('error', 'ข้อผิดพลาด'), ('critical', 'ร้ายแรง')], default='info', max_length=10, verbose_name='ระดับ')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้ที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'บันทึกระบบ',
                'verbose_name_plural': 'บันทึกระบบ',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'สมัครสมาชิก'), ('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ'), ('convert_image', 'แปลงภาพ'), ('export_png', 'ส่งออก PNG'), ('export_svg', 'ส่งออก SVG'), ('export_pdf', 'ส่งออก PDF'), ('export_eps', 'ส่งออก EPS'), ('admin_create_user', 'สร้างผู้ใช้ใหม่'), ('admin_delete_user', 'ลบผู้ใช้'), ('admin_edit_user', 'แก้ไขข้อมูลผู้ใช้'), ('admin_promote_user', 'เลื่อนตำแหน่งผู้ใช้'), ('admin_view_logs', 'ดูบันทึกการใช้งาน')], max_length=30, verbose_name='การกระทำ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เวลา')),
                ('details', models.JSONField(blank=True, help_text='ข้อมูลเพิ่มเติม เช่น ชื่อไฟล์ภาพที่แปลง, ขนาดไฟล์', null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'บันทึกการใช้งาน',
                'verbose_name_plural': 'บันทึกการใช้งาน',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_us_user_id_39428d_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_us_action_d05323_idx'), models.Index(fields=['timestamp'], name='accounts_us_timesta_d708d4_idx')],
            },
        ),
    ]
