# Generated by Django 5.1.4 on 2025-07-29 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_export_limit',
            field=models.IntegerField(default=10, help_text='จำนวนครั้งสูงสุดที่ส่งออกไฟล์ได้ต่อวัน', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='จำกัดการส่งออกต่อวัน'),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_exports_used',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='จำนวนการส่งออกที่ใช้วันนี้'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_export_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ส่งออกครั้งล่าสุด'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_exports',
            field=models.IntegerField(default=0, verbose_name='จำนวนการส่งออกทั้งหมด'),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_conversion_limit',
            field=models.IntegerField(default=50, help_text='เก็บไว้เพื่อ backward compatibility', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='จำกัดการแปลงต่อวัน (เก่า)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_conversions_used',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='จำนวนการแปลงที่ใช้วันนี้ (เก่า)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_conversion_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่แปลงครั้งล่าสุด (เก่า)'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('register', 'สมัครสมาชิก'), ('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ'), ('upload_image', 'อัปโหลดภาพ'), ('convert_image', 'แปลงภาพ'), ('export_png', 'ส่งออก PNG'), ('export_svg', 'ส่งออก SVG'), ('export_pdf', 'ส่งออก PDF'), ('export_eps', 'ส่งออก EPS'), ('admin_delete_user', 'ลบผู้ใช้'), ('admin_edit_user', 'แก้ไขข้อมูลผู้ใช้'), ('admin_promote_user', 'เลื่อนตำแหน่งผู้ใช้'), ('admin_view_logs', 'ดูบันทึกการใช้งาน')], max_length=30, verbose_name='การกระทำ'),
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(help_text='UUID จาก LocalStorage', max_length=36, verbose_name='Guest ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP Address สำรอง', verbose_name='IP Address')),
                ('daily_exports_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='จำนวนการส่งออกที่ใช้วันนี้')),
                ('last_export_date', models.DateField(blank=True, null=True, verbose_name='วันที่ส่งออกครั้งล่าสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง session')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='กิจกรรมล่าสุด')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Guest Session',
                'verbose_name_plural': 'Guest Sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['guest_id'], name='accounts_gu_guest_i_486dcb_idx'), models.Index(fields=['ip_address'], name='accounts_gu_ip_addr_efb543_idx'), models.Index(fields=['last_export_date'], name='accounts_gu_last_ex_434d84_idx')],
                'constraints': [models.UniqueConstraint(fields=('guest_id',), name='unique_guest_id')],
            },
        ),
    ]
