# Generated by Django 5.1.4 on 2025-08-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_daily_export_limit_user_daily_exports_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer_1',
            field=models.CharField(blank=True, help_text='คำตอบสำหรับคำถามข้อ 1 (จะถูกแปลงเป็นตัวพิมพ์เล็ก)', max_length=200, null=True, verbose_name='คำตอบคำถามข้อ 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer_2',
            field=models.CharField(blank=True, help_text='คำตอบสำหรับคำถามข้อ 2 (จะถูกแปลงเป็นตัวพิมพ์เล็ก)', max_length=200, null=True, verbose_name='คำตอบคำถามข้อ 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question_1',
            field=models.CharField(blank=True, help_text='คำถามสำหรับรีเซ็ตรหัสผ่าน', max_length=200, null=True, verbose_name='คำถามความปลอดภัยข้อ 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question_2',
            field=models.CharField(blank=True, help_text='คำถามสำหรับรีเซ็ตรหัสผ่าน', max_length=200, null=True, verbose_name='คำถามความปลอดภัยข้อ 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'ผู้ใช้ทั่วไป'), ('admin', 'ผู้ดูแลระบบ'), ('superuser', 'ซุปเปอร์ยูสเซอร์')], default='user', help_text='ระดับสิทธิ์การใช้งาน', max_length=10, verbose_name='ประเภทผู้ใช้'),
        ),
    ]
