# Generated by Django 5.1.4 on 2025-08-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_security_answer_1_user_security_answer_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('register', 'สมัครสมาชิก'), ('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ'), ('upload_image', 'อัปโหลดภาพ'), ('convert_image', 'แปลงภาพ'), ('export_png', 'ส่งออก PNG'), ('export_svg', 'ส่งออก SVG'), ('export_pdf', 'ส่งออก PDF'), ('export_eps', 'ส่งออก EPS'), ('admin_delete_user', 'ลบผู้ใช้'), ('admin_edit_user', 'แก้ไขข้อมูลผู้ใช้'), ('admin_promote_user', 'เลื่อนตำแหน่งผู้ใช้'), ('admin_view_logs', 'ดูบันทึกการใช้งาน'), ('password_reset', 'เปลี่ยนรหัสผ่าน'), ('security_questions_verified', 'ยืนยันคำถามความปลอดภัย')], max_length=30, verbose_name='การกระทำ'),
        ),
    ]
