# Generated by Django 5.1.4 on 2025-09-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('register', 'สมัครสมาชิก'), ('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ'), ('upload_image', 'อัปโหลดภาพ'), ('convert_image', 'แปลงภาพ'), ('export_png', 'ส่งออก PNG'), ('export_svg', 'ส่งออก SVG'), ('export_pdf', 'ส่งออก PDF'), ('export_eps', 'ส่งออก EPS'), ('admin_delete_user', 'ลบผู้ใช้'), ('admin_edit_user', 'แก้ไขข้อมูลผู้ใช้'), ('admin_promote_user', 'เลื่อนตำแหน่งผู้ใช้'), ('admin_view_logs', 'ดูบันทึกการใช้งาน'), ('password_reset', 'เปลี่ยนรหัสผ่าน'), ('security_questions_verified', 'ยืนยันคำถามความปลอดภัย'), ('admin_change_password', 'เปลี่ยนรหัสผ่านโดย Admin'), ('admin_edit_security_questions', 'แก้ไขคำถามความปลอดภัยโดย Admin'), ('profile_email_change', 'เปลี่ยนอีเมล (ผ่านโปรไฟล์)'), ('profile_password_change', 'เปลี่ยนรหัสผ่าน (ผ่านโปรไฟล์)'), ('profile_security_questions_change', 'เปลี่ยนคำถามความปลอดภัย (ผ่านโปรไฟล์)')], max_length=50, verbose_name='การกระทำ'),
        ),
    ]
