# Generated by Django 5.1.4 on 2025-09-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_conversion_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_conversions_used',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_conversion_date',
        ),
    ]
