# Generated by Django 5.1.4 on 2025-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_daily_conversion_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superuser', 'Super User')], default='user', help_text='ระดับสิทธิ์การใช้งาน', max_length=10, verbose_name='ประเภทผู้ใช้'),
        ),
    ]
