# Generated by Django 5.1.4 on 2025-09-28 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_export_limit',
            field=models.IntegerField(default=10, help_text='จำนวนครั้งสูงสุดที่ส่งออกไฟล์ได้ต่อวัน', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Daily Export Limit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_exports_used',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Daily Exports Used'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_export_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Export Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer_1',
            field=models.CharField(blank=True, help_text='คำตอบสำหรับคำถามข้อ 1 (จะถูกแปลงเป็นตัวพิมพ์เล็ก)', max_length=200, null=True, verbose_name='Security Answer 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer_2',
            field=models.CharField(blank=True, help_text='คำตอบสำหรับคำถามข้อ 2 (จะถูกแปลงเป็นตัวพิมพ์เล็ก)', max_length=200, null=True, verbose_name='Security Answer 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_1',
            field=models.CharField(blank=True, help_text='คำถามสำหรับรีเซ็ตรหัสผ่าน', max_length=200, null=True, verbose_name='Security Question 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_2',
            field=models.CharField(blank=True, help_text='คำถามสำหรับรีเซ็ตรหัสผ่าน', max_length=200, null=True, verbose_name='Security Question 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_conversions',
            field=models.IntegerField(default=0, verbose_name='Total Conversions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_exports',
            field=models.IntegerField(default=0, verbose_name='Total Exports'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superuser', 'Super User')], default='user', help_text='ระดับสิทธิ์การใช้งาน', max_length=10, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('register', 'สมัครสมาชิก'), ('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ'), ('upload_image', 'อัปโหลดภาพ'), ('convert_image', 'แปลงภาพ'), ('export_png', 'ส่งออก PNG'), ('export_svg', 'ส่งออก SVG'), ('export_pdf', 'ส่งออก PDF'), ('export_eps', 'ส่งออก EPS'), ('admin_delete_user', 'ลบผู้ใช้'), ('admin_edit_user', 'แก้ไขข้อมูลผู้ใช้'), ('admin_promote_user', 'เลื่อนตำแหน่งผู้ใช้'), ('admin_view_logs', 'ดูบันทึกการใช้งาน'), ('password_reset', 'เปลี่ยนรหัสผ่าน'), ('security_questions_verified', 'ยืนยันคำถามความปลอดภัย'), ('admin_change_password', 'เปลี่ยนรหัสผ่านโดย Admin'), ('admin_edit_security_questions', 'แก้ไขคำถามความปลอดภัยโดย Admin'), ('profile_email_change', 'เปลี่ยนอีเมล (ผ่านโปรไฟล์)'), ('profile_password_change', 'เปลี่ยนรหัสผ่าน (ผ่านโปรไฟล์)'), ('profile_security_questions_change', 'เปลี่ยนคำถามความปลอดภัย (ผ่านโปรไฟล์)')], max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='details',
            field=models.JSONField(blank=True, help_text='ข้อมูลเพิ่มเติม', null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
