# Generated by Django 5.1.4 on 2025-09-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options_alter_useractivitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answer_1',
            field=models.CharField(blank=True, help_text='Answer for security question 1', max_length=200, null=True, verbose_name='Security Answer 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer_2',
            field=models.CharField(blank=True, help_text='Answer for security question 2', max_length=200, null=True, verbose_name='Security Answer 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_1',
            field=models.CharField(blank=True, help_text='Security question for password recovery', max_length=200, null=True, verbose_name='Security Question 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_2',
            field=models.CharField(blank=True, help_text='Security question for password recovery', max_length=200, null=True, verbose_name='Security Question 2'),
        ),
    ]
