# Generated by Django 5.1.4 on 2025-09-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_security_answer_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemLog',
        ),
    ]
