# Generated by Django 5.1.4 on 2025-10-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_systemlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestsession',
            options={'ordering': ['-last_export_date'], 'verbose_name': 'Guest Session', 'verbose_name_plural': 'Guest Sessions'},
        ),
        migrations.RemoveField(
            model_name='guestsession',
            name='last_activity',
        ),
    ]
