# Generated by Django 5.1.4 on 2025-10-14 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_guestsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Session Created Date'),
        ),
        migrations.AlterField(
            model_name='guestsession',
            name='daily_exports_used',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Exports Used Today'),
        ),
        migrations.AlterField(
            model_name='guestsession',
            name='last_export_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Export Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address (must be unique)', max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
